# Site settings
title: Piráti v Královéhradeckém kraji
description: > # this means to ignore newlines until "baseurl:"
  Krajské sdružení Pirátů v Královéhradeckém kraji.
keywords: Piráti, komunální politika, Hradec Králové, Trutnov, Česká pirátská strana
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khk.pirati.cz" # the base hostname & protocol for your site
h1: "Piráti v Královéhradeckém kraji"
#ga: UA-54908007-1

permalink:     :title.html

# Build settings
markdown: kramdown
sass:
    sass_dir: assets/_sass
    style: :compressed
