# Site settings
title: Piráti v Chrudimi
description: > # this means to ignore newlines until "baseurl:"
  Piráti v Chrudimi
keywords: Piráti, komunální politika, Chrudim, Česká pirátská strana
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrudim.pirati.cz" # the base hostname & protocol for your site
h1: "Piráti v Chrudimi"
#ga: UA-54908007-1

permalink:     :title.html

# Build settings
markdown: kramdown
sass:
    sass_dir: assets/_sass
    style: :compressed
